export const MessageUserKeys = {
    SCHEDULING_CREATED: "Agendamento realizado com sucesso!",
    SCHEDULING_UPDATED: "Agendamento atualizado com sucesso!",
    SCHEDULING_DELETED: "Agendamento excluído com sucesso!",
    SCHEDULING_ERROR: "Ocorreu um erro ao processar o agendamento. Tente novamente.",
    SCHEDULING_DELETE_ERROR: "Ocorreu um erro ao tentar excluir o agendamento.",
    SERVICE_CREATED: "Serviço cadastrado com sucesso!",
    SERVICE_ERROR: "Ops !!!. Tente novamente.",
    SERVICE_NOT_FOUND: "Serviço não encontrado.",
    SERVICE_UPDATED: "Serviço atualizado com sucesso!",
    SERVICE_DELETED: "Serviço excluído com sucesso!",
    EMPLOYEE_CREATED: "Colaborador cadastrado com sucesso!",
    EMPLOYEE_CREATED_ERROR: "Erro ao cadastrar colaborador!",
    SERVICES_ASSOCIATED: "Serviços associados com sucesso!",
    SERVICES_ASSOCIATION_ERROR: "Erro ao associar serviços!",
    EMPLOYEE_CREATED: "Colaborador cadastrado com sucesso!",
    EMPLOYEE_CREATED_ERROR: "Erro ao cadastrar colaborador!",
    EMPLOYEE_UPDATED: "Colaborador atualizado com sucesso!",
    EMPLOYEE_UPDATE_ERROR: "Erro ao atualizar colaborador!",
    AFFINITY_REMOVED: "Afinidade removida com sucesso!",
    AFFINITY_REMOVED_ERROR: "Erro ao remover afinidade!",
    EMPLOYEE_NOT_FOUND: "Colaborador não encontrado.",
}
